### ISSUE TITLE
Specific Game Wireframe

### ISSUE THREAD

**Issue by shan-226** [COS301-SE-2024/GameOnConnect#10]
Do wireframe in figma

**Comment by MonikaTheiss** [comment]
Just a question... what does the add game button do? Other than that it looks good to me. @u22520016  what do you think?

**Comment by shan-226** [comment]
I remember us saying that there would be a button on the game that adds it to one of your currently playing games/wishlist so that's what the button is for.

**Comment by MonikaTheiss** [comment]
@shan-226  test comment

**Comment by MonikaTheiss** [comment]
@shan-226 test 2

**Comment by shan-226** [comment]
@MonikaTheiss Can you please allow me to close my own issues in future. If you want one of my issues closed let me know and I will do it.

**Comment by MonikaTheiss** [comment]
this problem was discussed on our group.
