### ISSUE TITLE
Design - Finish Wireframe of Specific Game Info

### ISSUE THREAD

**Issue by shan-226** [COS301-SE-2024/GameOnConnect#107]

**Comment by shan-226** [comment]
@u22520016  Can you please review this wireframe for me

**Comment by u22520016** [comment]
I left some comments on Figma.  The design is not done yet, so do not close this issue yet.

**Comment by shan-226** [comment]
@u22520016  I made some changes based on your comments. Can you please review it again and let me know.

**Comment by shan-226** [comment]
@u22520016 I added a light mode design. Can you please review the design for this page please(Light and Dark).
