### ISSUE TITLE
Finish SignUp/Login design

### ISSUE THREAD

**Issue by u22520016** [COS301-SE-2024/GameOnConnect#111]

**Comment by u22520016** [comment]
Dark mode is done

**Comment by u22520016** [comment]
@pieryvdl @MonikaTheiss @shan-226 Please review the design on Figma (Final page).

**Comment by MonikaTheiss** [comment]
Looks great! Thank you 😄 @u22520016

**Comment by shan-226** [comment]
It looks good! Why are we not entering the users name during signup?

**Comment by MonikaTheiss** [comment]
Because name is optional
