### ISSUE TITLE
Create coding standards document

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#120]

**Comment by shan-226** [comment]
@MonikaTheiss Please review this on the Wiki for me.

**Comment by MonikaTheiss** [comment]
Cool , thank you @shan-226 !
I have read through it , and I had 2 questions: the first question was do we need the table of contents? Because when I opened the coding standards for the first time, I thought I had the wrong version since there were headings, but no content, until I scrolled down.
And then just a small thing, which either we can change in the code or in the wiki, depending on what everyone thinks. The const naming , I don't think I have seen us make the const var's name in capital letters 😅

**Comment by shan-226** [comment]
@MonikaTheiss I removed the table of contents. What is the current format used for consts. I can change the document to reflect that. Unless you would rather change the code?

**Comment by MonikaTheiss** [comment]
Cool , thank you ! Looks very cool, thank you for the amount of work  you put in it. 
For consts we used PascalCase

**Comment by shan-226** [comment]
I updated it to use PascalCase. Let me know if there is anything else that needs to be added.

**Comment by MonikaTheiss** [comment]
Looks good! Thank you
