### ISSUE TITLE
Time to load bug

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#134]
Time to load the profile page + banner specifically take a very long time to load - maybe store this info on the device?

**Comment by pieryvdl** [comment]
After testing i intend on looking into this.

**Comment by MonikaTheiss** [comment]
Can we close this issue @pieryvdl ? I see you linked the pull request to it.. don't know why it didnt close it automatically

**Comment by pieryvdl** [comment]
Yes. We can close it.
