### ISSUE TITLE
view friend request page 

### ISSUE THREAD

**Issue by LeratoKgomo** [COS301-SE-2024/GameOnConnect#165]
Its the page where the user can see their friend requests.
please let @LeratoKgomo or  @pieryvdl  know when you start on this

**Comment by MonikaTheiss** [comment]
@LeratoKgomo I will start working on this now

**Comment by LeratoKgomo** [comment]
thank you i already made the backend functions so you can just focus on the UI

**Comment by MonikaTheiss** [comment]
Awesome! Thank you

**Comment by MonikaTheiss** [comment]
@pieryvdl is taking this over

**Comment by pieryvdl** [comment]
@LeratoKgomo is adding the backend functions
