### ISSUE TITLE
Add service contracts

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#17]

**Comment by MonikaTheiss** [comment]
can anyone just read through the service contracts please? And let me know what you think.. I'm not too sure I am happy with it at the moment, but I dont know what is missing

**Comment by MonikaTheiss** [comment]
@shan-226  and @pieryvdl please have a look at the service contracts

**Comment by MonikaTheiss** [comment]
@shan-226 I have added more information, please let me know what you think

**Comment by shan-226** [comment]
@MonikaTheiss It looks really good. Maybe just add the parameters/json data that is returned from the RAWG API.

**Comment by MonikaTheiss** [comment]
@shan-226  I have added your suggested data. Please let me know if it is better now?

**Comment by shan-226** [comment]
It looks good!
