### ISSUE TITLE
update Architecture strategies and quantification 

### ISSUE THREAD

**Issue by LeratoKgomo** [COS301-SE-2024/GameOnConnect#174]

**Comment by LeratoKgomo** [comment]
@MonikaTheiss  and @shan-226 
May you please review the Quality requirements section. 
I work on word then transferred to wiki so please let me know of any mistakes you notice.

**Comment by MonikaTheiss** [comment]
I just have a question: For the performance requirement, you mentioned frames per second. I believe that is for videos/ games. Coul dyou perhaps explain what we would need frames per seconds for?
The rest looks good! Thank you very much @LeratoKgomo 😄

**Comment by shan-226** [comment]
It looks really good!
