### ISSUE TITLE
Add Architecture design strategy 

### ISSUE THREAD

**Issue by LeratoKgomo** [COS301-SE-2024/GameOnConnect#177]
- chosen strategy 
- justification

**Comment by LeratoKgomo** [comment]
@MonikaTheiss and @shan-226
May you please review the Architecture design strategy section 
I work on word then transferred to wiki so please let me know of any mistakes you notice

**Comment by MonikaTheiss** [comment]
Looks good to me ! Thank you @LeratoKgomo

**Comment by shan-226** [comment]
It looks really good!
