### ISSUE TITLE
Add caching to game info page

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#180]

**Comment by MonikaTheiss** [comment]
@piery I can't remember what we discussed about this.. are we leaving this for now?

**Comment by pieryvdl** [comment]
> @pieryvdl I can't remember what we discussed about this.. are we leaving this for now?

As far as I can recall yes, but I can look into it in this coming week.

**Comment by pieryvdl** [comment]
This solution has been merged in.
