### ISSUE TITLE
Specify functional requirements satisfying use cases

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#22]

**Comment by MonikaTheiss** [comment]
@pieryvdl  can you please have review  the requirements on the wiki under the functional requirements page.

**Comment by pieryvdl** [comment]
Hi, I've had a look, will explain in the meeting later today. I think we might need to expand a bit on the sign-up and what browsing a list of games entails. I don't mind doing it and helping with that later today. Also for the diagrams they look great! We should maybe just add Firebase as the Database on the other side.
