### ISSUE TITLE
Add subsystems

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#23]

**Comment by MonikaTheiss** [comment]
@shan-226  and @LeratoKgomo please also review the subsystem diagrams. Let me know if I can change anything

**Comment by shan-226** [comment]
@MonikaTheiss  It looks good to me.

**Comment by LeratoKgomo** [comment]
@MonikaTheiss  not sure about this but would the searching for a game be a subsystem

**Comment by MonikaTheiss** [comment]
@LeratoKgomo  I'm not sure if we are implementing search,filter and sort, because of time. We can discuss this during today's meeting though. I know Piery also wanted to discuss the diagrams
