### ISSUE TITLE
Code Coverage Badge

### ISSUE THREAD

**Issue by pieryvdl** [COS301-SE-2024/GameOnConnect#26]

**Comment by MonikaTheiss** [comment]
Is it supposed to still show unknown? If it is, you can merge

**Comment by pieryvdl** [comment]
I think it shows unknown because it is on Develop and not in main. From what I cna tell it shows the coverage in main. But I can't see unless we merge it to main.

**Comment by MonikaTheiss** [comment]
Okay cool then you can merge

**Comment by pieryvdl** [comment]
Sweet merging Dev to main.
