### ISSUE TITLE
Add Architectural Patterns

### ISSUE THREAD

**Issue by LeratoKgomo** [COS301-SE-2024/GameOnConnect#31]

**Comment by LeratoKgomo** [comment]
@MonikaTheiss @pieryvdl 
May you please review the Architecture section.
I worked on word then transferred to wiki so please let me know of any mistakes you notice.

**Comment by MonikaTheiss** [comment]
Looks very good! Just a small thing I saw: under the MVC pattern, it is not mentioned how we would use it for GameOnConnect like it does under the rest. Is there a reason for this?
Thank you for all the work you put into this wiki document @LeratoKgomo

**Comment by LeratoKgomo** [comment]
i could really find a solid application 

this was what i had i just thought it doesnt really explain but let me know if i should add it 
•	Application in GameOnConnect: MVC is used in the Flutter app to manage state and UI components, ensuring a responsive and intuitive user experience.

**Comment by MonikaTheiss** [comment]
> i couldnt really find a solid application
> 
> this was what i had i just thought it doesnt really explain but let me know if i should add it • Application in GameOnConnect: MVC is used in the Flutter app to manage state and UI components, ensuring a responsive and intuitive user experience.

yeah I think you can add that
