### ISSUE TITLE
Frontend - Create Login page

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#39]

**Comment by pieryvdl** [comment]
@MonikaTheiss @u22520016 The login Page has now been made. Please see it on my branch feat/Authentication1

**Comment by MonikaTheiss** [comment]
Login page looks good ! Had a few questions while running it, will send you a message

**Comment by u22520016** [comment]
I will review this page as soon as I get the time

**Comment by pieryvdl** [comment]
I see you've made some updates, I will go and change the page I made.

**Comment by pieryvdl** [comment]
Keeping the current frontend page, I will go and add themes.
