### ISSUE TITLE
Update user manual

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#398]

**Comment by MonikaTheiss** [comment]
@pieryvdl is the user manual done for this demo?

**Comment by pieryvdl** [comment]
@MonikaTheiss I updated it as far as I could with the pages that were done. Planned to revise it so that it is ready for Demo. I would say the wiki is 90% complete. One or 2 more pages to add.

**Comment by pieryvdl** [comment]
@MonikaTheiss I added more pages to user manual. I believe it is done. now.

**Comment by pieryvdl** [comment]
This has been done.
