### ISSUE TITLE
Create SRS document

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#5]
- [x] Required for demo 1 - look at demo instructions for more detail. And remember to add a link to this document to the README

- [x] #14
- [x] #15
- [x] #16
- [ ] #17
- [x] #18
- [ ] #19
- [x] #20

**Comment by pieryvdl** [comment]
I created the SRS Doc can we close this issue? :)

**Comment by LeratoKgomo** [comment]
Maybe we should close it once the document is actually done?

**Comment by MonikaTheiss** [comment]
@pieryvdl because this issue tracks all the smaller issues ( small parts that need to be done on the documentation ) I would not close this just yet

**Comment by pieryvdl** [comment]
@MonikaTheiss Okay cool. I'll move it to In Progress.
