### ISSUE TITLE
Google sign in issue

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#546]
When signing in with google, using an already used email account, you cannot log in with that email and password

**Comment by pieryvdl** [comment]
I believe this has been fixed? Or we will not work on it?

**Comment by MonikaTheiss** [comment]
> I believe this has been fixed? Or we will not work on it? [@MonikaTheiss](https://github.com/MonikaTheiss)

It has not been fixed yet, we still need to fix this at some point, but I don't think it is a huge issue.
