### ISSUE TITLE
Frontend - Bottom Nav Bar

### ISSUE THREAD

**Issue by shan-226** [COS301-SE-2024/GameOnConnect#60]
- [ ] #121
- [ ] Backend - Add navigation

**Comment by shan-226** [comment]
@u22520016 Can you please review the bottom nav bar I created. Branch: feat/BottomNavBar

**Comment by MonikaTheiss** [comment]
Looks really cool ! Thank you 😄 
I'm happy with how it looks. If @u22520016 is fine with it , you can create a pull request so we can officially review it

**Comment by u22520016** [comment]
Looks perfect for now!  I personally think the middle button should be circle but its fine for now since the design will be changing anyways in the near future👍

**Comment by u22520016** [comment]
I finalized the navbar design on Figma
