### ISSUE TITLE
Customize page - update profile picture integration

### ISSUE THREAD

**Issue by MonikaTheiss** [COS301-SE-2024/GameOnConnect#94]

**Comment by MonikaTheiss** [comment]
It does now update the profile picture in the database and changes the profile pic. it does however update the database when a new profile picture is selected, and not when clicking save changes.. don't know if that is a problem.

**Comment by LeratoKgomo** [comment]
Its also possible that the user selects a picture but they change their mind and dont want to change the picture. The changes should only be updated on the database once the user clicks on the save button. If you are unable to do it on your side please let me know then ill look into it.

**Comment by MonikaTheiss** [comment]
I will take a look again later, according to how I understand the code, it is supposed to only update on the database when the user clicks save changes , but it doesnt do that when I test it, so I'll look into it later
